name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Image
      run: docker build -t maezzedine/abjad-ui:latest -t maezzedine/abjad-ui:${{ github.run_number }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      if: github.event_name == 'push'
      with:
        username: maezzedine
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Publish Image
      if: github.event_name == 'push'
      run: docker push maezzedine/abjad-ui --all-tags
