name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Lexer Image
      run: docker build --build-arg app_name=lexer -t maezzedine/abjad-lex-ui:latest -t maezzedine/abjad-lex-ui:${{ github.run_number }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      if: github.event_name == 'push'
      with:
        username: maezzedine
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Publish Lexer Image
      if: github.event_name == 'push'
      run: docker push maezzedine/abjad-lex-ui --all-tags
